import sys
sys.path.insert(0,'whj_code2/cogdl_fork/cogdl')

from cogdl import experiment

experiment(task="node_classification", dataset="rd2cd_Github", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Elliptic", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Film", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Wiki", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Clothing", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Electronics", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Dblp", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Yelpchi", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Alpha", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Weibo", model="gcn")
experiment(task="node_classification", dataset="rd2cd_bgp", model="gcn")
experiment(task="node_classification", dataset="rd2cd_ssn5", model="gcn")
experiment(task="node_classification", dataset="rd2cd_ssn7", model="gcn")
experiment(task="node_classification", dataset="rd2cd_chameleon", model="gcn")
experiment(task="node_classification", dataset="rd2cd_squirrel", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Aids", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Nba", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Wisconsin", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Texas", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Cornell", model="gcn")
experiment(task="node_classification", dataset="rd2cd_Pokec_z", model="gcn")
